version: '3'

services:
  axon1:
    build: .
    restart: always
    privileged: true
    ports:
      - 8000:8000
      - 8900:8100
    volumes:
      - ./devtools:/app/devtools
      - ./target/release:/app/build
    networks:
      - axon-net
    command: /app/build/axon -c=/app/devtools/chain/nodes/node_1.toml -g=/app/devtools/chain/nodes/genesis_multi_nodes.json

  axon2:
    build: .
    restart: always
    privileged: true
    ports:
      - 8001:8001
      - 8901:8100
    volumes:
      - ./devtools:/app/devtools
      - ./target/release:/app/build
    networks:
      - axon-net
    command: /app/build/axon -c=/app/devtools/chain/nodes/node_2.toml -g=/app/devtools/chain/nodes/genesis_multi_nodes.json

  axon3:
    build: .
    restart: always
    privileged: true
    ports:
      - 8002:8002
      - 8902:8100
    volumes:
      - ./devtools:/app/devtools
      - ./target/release:/app/build
    networks:
      - axon-net
    command: /app/build/axon -c=/app/devtools/chain/nodes/node_3.toml -g=/app/devtools/chain/nodes/genesis_multi_nodes.json

  axon4:
    build: .
    restart: always
    privileged: true
    ports:
      - 8003:8003
      - 8903:8100
    volumes:
      - ./devtools:/app/devtools
      - ./target/release:/app/build
    networks:
      - axon-net
    command: /app/build/axon -c=/app/devtools/chain/nodes/node_4.toml -g=/app/devtools/chain/nodes/genesis_multi_nodes.json

networks:
  axon-net:
